---
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create database
  mysql_db:
    name: system_stats
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create logs table
  mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    query: |
      CREATE TABLE IF NOT EXISTS logs (
        id INT AUTO_INCREMENT PRIMARY KEY,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        cpu_usage FLOAT,
        memory_usage FLOAT
      );
...