---
- name: Ensure cron package is installed on Amazon Linux
  yum:
    name: cronie
    state: present
  when: ansible_distribution == "Amazon"
  become: true

- name: Start and enable cron service
  service:
    name: crond
    state: started
    enabled: yes
  when: ansible_distribution == "Amazon"
  become: true
...