---
- name: Ensure cron is installed
  package:
    name: cron
    state: present
  become: true
  
- name: Schedule script via cron
  cron:
    name: "System Stats Logger"
    job: "/usr/bin/python3 /home/ec2-user/system_logger.py"
    minute: "*/5"
...