---
- name: Ensure cronie is installed on Amazon Linux
  yum:
    name: cronie
    state: present
  when: ansible_distribution == "Amazon"
  become: true

- name: Schedule script via cron
  cron:
    name: "System Stats Logger"
    job: "/usr/bin/python3 /home/ec2-user/system_logger.py"
    minute: "*/5"
  become: true
...