---
- name: Install Python 3 and pip
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install required Python packages
  pip:
    name:
      - psutil
      - mysql-connector-python
    executable: pip3

- name: Copy Python script to Jenkins Master
  copy:
    src: ../files/system_logger.py
    dest: /home/ubuntu/system_logger.py  # Adjusted path
    mode: '0755'

    
...
