---
- name: Install Python 3
  yum:
    name: python3
    state: present

- name: Install required Python packages
  pip:
    name:
      - mysql-connector-python
      - psutil
    state: present

- name: Copy Python script to EC2
  copy:
    src: ../files/system_logger.py
    dest: /home/ec2-user/system_logger.py
    mode: '0755'
    
...
