---
- name: Provision Jenkins Agents
  hosts: jenkins_agents
  become: true
  vars_files:
    - vars.yml
  vars:
    ansible_ssh_private_key_file: /home/ubuntu/bee.pem  # Ensure this path is correct
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"  # Use the variable to reference the key

  roles:
    - install_python
    - install_cron
    - schedule_script

- name: Setup MySQL Server
  hosts: g2
  become: true
  vars_files:
    - vars.yml
  vars:
    ansible_ssh_private_key_file: /home/ubuntu/bee.pem  # Ensure this path is correct
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"  # Use the variable to reference the key
  roles:
    - setup_mysql
