---
- name: Provision Jenkins Agents
  hosts: jenkins_agents
  become: true
  vars_files:
    - vars.yml
  vars:
    ansible_ssh_private_key_file: /var/lib/jenkins/bee.pem  # Updated path
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

  roles:
    - install_python
    - install_cron
    - schedule_script

- name: Setup MySQL Server
  hosts: g2
  become: true
  vars_files:
    - vars.yml
  vars:
    ansible_ssh_private_key_file: /var/lib/jenkins/bee.pem  # Updated path
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

  roles:
    - setup_mysql
    
...